
# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}

# mybatis
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: mapper/**/*.xml
  type-aliases-package: cobook.buddywisdom.**.domain # xml파일 result type에 패키지명을 생략할 수 있도록 alias 설정

# springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui  # swagger-ui custom path
  api-docs:
    path: /api-docs  # JSON format endpoint custom path

# 로깅 레벨 설정
logging.level:
  cobook.buddywisdom.**: DEBUG

jwt:
  header: Authorization
  secret: ${{ secrets.JWT_SECRET }}
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간